elasticsearch:
    build: elasticsearch/
# Uncomment for persitent storage and/or elasticsearch special configuration 
#     volumes:
#        - ./elasticsearch/data:/usr/share/elasticsearch/data
#        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    command: elasticsearch 
    ports:
        - "9200:9200"
        - "9300:9300"

logstash:
    image: logstash:latest
    volumes:
        - ./logstash/config:/config
    command: logstash -f /config/logstash.conf
    ports:
        - "5000:5000"
    links:
        - elasticsearch
        
kibana:
     build: kibana/
     volumes:
        - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
     ports:
        - "5601:5601"
     links:
        - elasticsearch